micronaut:
  application:
    name: grpcfrete
  server:
    port: 8085

grpc:
  server:
    health:
      enabled: true

endpoints:
  all:
    #port: 8085
    sensitive: true
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
